labs/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/login', to: 'devise/sessions#login'
    get '/signup', to: 'devise/registrations#sign_up'
    get '/logout', to: 'devise/sessions#destroy'
  end

  resources :libraries
  resources :books
  delete 'books/:id', to: 'books#destroy', as: :destroy_book
  resources :authors
  resources :genres
  resources :reader_cards
  get 'search_lib', to: 'search#search_lib'
  get 'search_book', to: 'search#search_book'
  get 'search_author', to: 'search#search_author'
  get 'search_genre', to: 'search#search_genre'
  get 'search_card', to: 'search#search_card'
  get 'export_libraries_csv', to: 'libraries_csv#export', as: 'export_libraries_csv'
  get 'export_pdf_library', to: 'pdf_downloader#export_library', as: 'export_pdf_library'
  get 'export_pdf_author', to: 'pdf_downloader#export_author', as: 'export_pdf_author'
  get 'export_pdf_genre', to: 'pdf_downloader#export_genre', as: 'export_pdf_genre'
  get 'export_pdf_book', to: 'pdf_downloader#export_book', as: 'export_pdf_book'
  get 'export_pdf_card', to: 'pdf_downloader#export_reader_card', as: 'export_pdf_card'
  get 'export_pdf_lib_id', to: 'pdf_lib_id#export_lib_id'
end

labs/app/models/genre.rb
# frozen_string_literal: true

# Model class for genres
class Genre < ApplicationRecord
  belongs_to :book

  validates :name, presence: true
end

labs/app/controllers/genres_controller.rb
# frozen_string_literal: true

# Controls the behavior for managing genres.
class GenresController < ApplicationController
  before_action :set_genre, only: %i[show edit update destroy]

  def index
    @genres = Genre.all.page(params[:page]).per(10)
  end

  def show; end

  def new
    @genre = Genre.new
  end

  def edit; end

  def create
    @genre = Genre.new(genre_params)
    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: t('notices.genre_created') }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: t('notices.genre_updated') }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: t('notices.genre_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name, :description)
  end
end

labs/app/helpers/genre_helper.rb
# frozen_string_literal: true

# Module to hold helper methods related to genres
module GenreHelper
end

labs/app/views/genres/edit.html.erb
<h1>Edit Genre</h1>

<%= form_with(model: @genre, class: "genre-form", method: "patch") do |form| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>
      <ul>
        <% @genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :book_id %>
    <%= form.collection_select :book_id, Book.all, :id, :title, {prompt: true}, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit "Update Genre", class: "btn btn-primary" %>
  </div>
<% end %>

labs/app/views/genres/index.html.erb
<h1>Genres</h1>
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Book</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @genres.each do |genre| %>
    <tr>
      <td><%= genre.name %></td>
      <td><%= link_to genre.book.title, book_path(genre.book) %></td>
      <td><%= link_to 'Show', genre %></td>
      <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
      <td><%= link_to 'Destroy', genre_path(genre), method: :delete,
                      data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<br>
<%= paginate @genres %>
<br><br>
<%= link_to "Export PDF", export_pdf_genre_path, class: "btn btn-primary" %>
<br><br>
<%= link_to 'New Genre', new_genre_path, class: "btn btn-primary" %>

labs/app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= form_with(model: @genre, class: "genre-form") do |form| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>
      <ul>
        <% @genre.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :book_id %>
    <%= form.collection_select(:book_id, Book.all, :id, :title, { prompt: true }, class: "form-control") %>
  </div>

  <div class="actions">
    <%= form.submit "Create Genre", class: "btn btn-primary" %>
  </div>
<% end %>

labs/app/views/genres/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>
<p>
  <strong>Book:</strong>
  <%= link_to @genre.book.title, book_path(@genre.book) %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre), class: "btn btn-primary" %> |
<%= link_to 'Back', genres_path, class: "btn btn-secondary" %>