labs/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/login', to: 'devise/sessions#login'
    get '/signup', to: 'devise/registrations#sign_up'
    get '/logout', to: 'devise/sessions#destroy'
  end

  resources :libraries
  resources :books
  delete 'books/:id', to: 'books#destroy', as: :destroy_book
  resources :authors
  resources :genres
  resources :reader_cards
  get 'search_lib', to: 'search#search_lib'
  get 'search_book', to: 'search#search_book'
  get 'search_author', to: 'search#search_author'
  get 'search_genre', to: 'search#search_genre'
  get 'search_card', to: 'search#search_card'
  get 'export_libraries_csv', to: 'libraries_csv#export', as: 'export_libraries_csv'
  get 'export_pdf_library', to: 'pdf_downloader#export_library', as: 'export_pdf_library'
  get 'export_pdf_author', to: 'pdf_downloader#export_author', as: 'export_pdf_author'
  get 'export_pdf_genre', to: 'pdf_downloader#export_genre', as: 'export_pdf_genre'
  get 'export_pdf_book', to: 'pdf_downloader#export_book', as: 'export_pdf_book'
  get 'export_pdf_card', to: 'pdf_downloader#export_reader_card', as: 'export_pdf_card'
  get 'export_pdf_lib_id', to: 'pdf_lib_id#export_lib_id'
end

labs/app/models/library.rb
# frozen_string_literal: true

# Model class for libraries
class Library < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
end

labs/app/controllers/libraries_controller.rb
# frozen_string_literal: true

# Controls the behavior for managing libraries.
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[show edit update destroy]

  def index
    @user = current_user
    @libraries = Library.all.page(params[:page]).per(10)
  end

  def show; end

  def new
    @library = Library.new
  end

  def edit; end

  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: t('notices.library_created') }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: t('notices.library_updated') }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @library = Library.find(params[:id])
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_path, notice: t('notices.library_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_library
    @library = Library.find(params[:id])
  end

  def library_params
    params.require(:library).permit(:name, :address)
  end
end

labs/app/helpers/libraries_helper.rb
# frozen_string_literal: true

# Module to hold helper methods related to libraries
module LibrariesHelper
end

labs/app/views/libraries/edit.html.erb
<h1>Edit Library</h1>

<%= form_with(model: @library, class: "library-form", method: "patch") do |form| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% @library.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Update Library", class: "btn btn-primary" %>
  </div>

<% end %>

labs/app/views/libraries/index.html.erb
<% if user_signed_in? %>
  <div>Welcome <%= current_user.email %></div>
<% end %>

<h1>Libraries</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @libraries.each do |library| %>
    <tr>
      <td><%= library.name %></td>
      <td><%= library.address %></td>
      <td><%= link_to 'Show', library %></td>
      <td><%= link_to 'Edit', edit_library_path(library) %></td>
      <td><%= link_to 'Destroy', library_path(library), method: :delete,
                      data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= paginate @libraries %>
<br>
<%= link_to 'New Library', new_library_path, class: "btn btn-primary" %>
<br><br>
<%= link_to "Export Libraries CSV", export_libraries_csv_path, class: "btn btn-primary" %>
<br><br>
<%= link_to "Export PDF", export_pdf_library_path, class: "btn btn-primary" %>
<br><br>
<%= link_to "Logout", logout_path, method: :get %>

labs/app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= form_with(model: @library, class: "library-form") do |form| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% @library.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Library", class: "btn btn-primary" %>
  </div>
<% end %>

labs/app/views/libraries/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @library.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @library.address %>
</p>

<p>
  <strong>Year:</strong>
  <%= @library.year %>
</p>

<%= link_to 'Edit', edit_library_path(@library), class: "btn btn-primary" %> |
<%= link_to 'Back', libraries_path, class: "btn btn-secondary" %>
<br><br>
<%= link_to "Export PDF", export_pdf_lib_id_path(id: @library.id), class: "btn btn-primary" %>