labs/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/login', to: 'devise/sessions#login'
    get '/signup', to: 'devise/registrations#sign_up'
    get '/logout', to: 'devise/sessions#destroy'
  end

  resources :libraries
  resources :books
  delete 'books/:id', to: 'books#destroy', as: :destroy_book
  resources :authors
  resources :genres
  resources :reader_cards
  get 'search_lib', to: 'search#search_lib'
  get 'search_book', to: 'search#search_book'
  get 'search_author', to: 'search#search_author'
  get 'search_genre', to: 'search#search_genre'
  get 'search_card', to: 'search#search_card'
  get 'export_libraries_csv', to: 'libraries_csv#export', as: 'export_libraries_csv'
  get 'export_pdf_library', to: 'pdf_downloader#export_library', as: 'export_pdf_library'
  get 'export_pdf_author', to: 'pdf_downloader#export_author', as: 'export_pdf_author'
  get 'export_pdf_genre', to: 'pdf_downloader#export_genre', as: 'export_pdf_genre'
  get 'export_pdf_book', to: 'pdf_downloader#export_book', as: 'export_pdf_book'
  get 'export_pdf_card', to: 'pdf_downloader#export_reader_card', as: 'export_pdf_card'
  get 'export_pdf_lib_id', to: 'pdf_lib_id#export_lib_id'
end

labs/app/models/book.rb
# frozen_string_literal: true

# Model class for books
class Book < ApplicationRecord
  belongs_to :library
  has_many :genres, dependent: :destroy
  has_many :authors, dependent: :destroy

  validates :title, presence: true
  validates :year, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

labs/app/controllers/books_controller.rb
# frozen_string_literal: true

# Controls the behavior for managing books.
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @books = Book.all.page(params[:page]).per(10)
  end

  def show; end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: t('notices.book_created') }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: t('notices.book_updated') }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: t('notices.book_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :year, :library_id)
  end
end

labs/app/helpers/books_helper.rb
# frozen_string_literal: true

# Module to hold helper methods related to books
module BooksHelper
end

labs/app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :library %>
    <%= form.collection_select(:library_id, Library.all, :id, :name, {}, {class: 'form-control'}) %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

labs/app/views/books/index.html.erb
<h1>Books</h1>
<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Year</th>
    <th>Library</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.year %></td>
      <td><%= book.library.name %></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book_path(book), method: :delete,
                      data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<br>
<%= paginate @books %>
<br><br>
<%= link_to "Export PDF", export_pdf_book_path, class: "btn btn-primary" %>
<br><br>
<%= link_to 'New Book', new_book_path, class: "btn btn-primary" %>

labs/app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :library %>
    <%= form.collection_select(:library_id, Library.all, :id, :name, {}, {class: 'form-control'}) %>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

labs/app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p><strong>Year:</strong> <%= @book.year %></p>

<p><strong>Library:</strong> <%= link_to @book.library.name, @book.library %></p>

<%= link_to 'Edit', edit_book_path(@book), class: "btn btn-primary" %>
<%= link_to 'Back', books_path, class: "btn btn-secondary" %>
<%= link_to 'Delete', destroy_book_path(@book), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>